sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      env: BUILD=1
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - mkdir .whl
        - python setup.py bdist_wheel
        - mv dist/*.whl .whl/

deploy:
  provider: bintray
  file: "descriptor.json"
  user: robertnishihara
