sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: UPLOAD_TO_S3=1
    install:
    - mkdir .whl
    - echo "AAAAAA" >> .whl/file1.txt
    - echo "BBBBBB" >> .whl/file2.txt
deploy:
  provider: s3
  access_key_id: AKIAU6DMUCJUFL3EX3SM
  secret_access_key:
    secure: cs/CtgvbLEm+gr7WZI/CP531a38lfqvZ0qrmkB4fy5/5MMLI+/kLxJlKQj6FVXdg1k0bJ62fUT08Wk1ExpL9pocUpAcdFn9v2gfrTM9ENrwik1XoIdNgbd8d8ooUEzLWpi1b19znlgzUF7oxYOD6Ib1GUhONlnHfiXUHg6A4CcRgZwvBtRyzpcZQC13x8glsmZBJoBAiDG3ydaFvgKOPzhrIZxUon93yRaG1ZO7VBOgGn6Pj6gMEl4s4N1OWxquXZm3nTXz8l0uF0OOZ+r2zoeZCrXkugl11753PgNZYMq9iuzTyEHDctF6052UdTd0xNUF8/aA/yEdWDuGDmMqwKPrXfLC6LyyNwnGnuF+GLtY7f3MfeueKJJ6fScFTUM6W+3LeMZkLSX6WPFOVHQFaK1d8tDnfT+uoNf95Jmr0WDFENF/oTNN80vmAYSNrZbArgdCM8t2DTerXJLMW6gCTnNUPXxhzCU04MIXl1FtyRCtml4v46fPuQBDkUJHruhOWpr4Jq248egpKFSUqjIVm24JtDqykWQTEJ0jhIZaEWTaZZnPsoDxJMO9uMA1jOsabCfXwDPJokQys+Hu16IW47ISFtyxdpeqUPeSpfPZdJjyNXLNKaYdAX/KcLzjude6YGesqv6WYBbvhgFM+FiyoHHeHveAbyP6nFEtgIN2F4ow=
  acl: public_read
  bucket: ray-wheels
  region: us-west-2
  skip_cleanup: true
  local_dir: ".whl"
  upload-dir: "$TRAVIS_COMMIT"
  only:
  - master
  on:
    repo: robertnishihara/testtravistobintray
    condition: "$UPLOAD_TO_S3 = 1 || $DEFINITELY_UPLOAD_TO_S3 = 1"
